---
- name: "Ensure ACME is set up"
  ansible.builtin.include_tasks: setup.yml

- name: "Ensure certificates are generated"
  ansible.builtin.include_tasks: certificates.yml
  loop: "{{ acme_domain_names }}"
  loop_control:
    loop_var: domain_name
