---
- name: "Ensure Root CAs are downloaded from Let's Encrypt"
  ansible.builtin.get_url:
    url: "{{ acme_download.url }}"
    dest: "/tmp/{{ acme_download.filename }}"
    mode: '0644'
  loop:
    - url: 'https://letsencrypt.org/certs/isrgrootx1.pem'
      filename: 'isrgrootx1.pem'
    - url: 'https://letsencrypt.org/certs/isrg-root-x2.pem'
      filename: 'isrg-root-x2.pem'
  loop_control:
    loop_var: acme_download

- name: "Ensure Root CAs are uploaded to SRX"
  juniper.device.file_copy:
    protocol: scp
    remote_dir: "/var/tmp/"
    local_dir: "/tmp/"
    action: put
    file: "{{ acme_upload.filename }}"
  loop:
    - filename: 'isrgrootx1.pem'
    - filename: 'isrg-root-x2.pem'
  loop_control:
    loop_var: acme_upload

- name: "Ensure ACME and security zone configuration are applied"
  juniper.device.config:
    load: "replace"
    format: "text"
    template: "{{ role_path }}/templates/acme_config.j2"
    comment: "Configured ACME & security zone via Ansible"
    vars: {}

- name: "Ensure Let's Encrypt Root CAs are loaded into Junos"
  juniper.device.command:
    commands:
      - "request security pki ca-certificate load ca-profile ISRG_Root_X1 filename /var/tmp/isrgrootx1.pem"
      - "request security pki ca-certificate load ca-profile ISRG_Root_X2 filename /var/tmp/isrg-root-x2.pem"
    formats: "json"
    # Set to json to bypass these issues:
    # https://github.com/Juniper/ansible-junos-stdlib/issues/622
    # https://github.com/Juniper/ansible-junos-stdlib/issues/808

- name: "Ensure key pairs are generated"
  juniper.device.command:
    commands:
      - >
        request security pki generate-key-pair size {{ acme_key_size }}
        type {{ acme_key_type }}
        acme-key-id {{ acme_key_id }}
      - >
        request security pki generate-key-pair size {{ acme_key_size }}
        type {{ acme_key_type }}
        certificate-id {{ acme_certificate_id }}

- name: "Check if ACME certificate already exists"
  juniper.device.command:
    commands:
      - "show security pki local-certificate"
    formats: "json"
  register: acme_cert_check

- name: "Request ACME certificate"
  juniper.device.command:
    commands:
      - >
        request security pki local-certificate enroll acme
        acme-key-id {{ acme_key_id }}
        certificate-id {{ acme_certificate_id }}
        ca-profile {{ acme_ca_profile_name }}
        domain-names {{ acme_domain_name }}
        email {{ acme_email }}
        letsencrypt-enrollment
        yes terms-of-service agree
    formats: "json"
  when: acme_certificate_id not in acme_cert_check.stdout
