---
- name: Converge
  hosts: all
  tasks:
    - name: "Include iambryant.junos.acme"
      ansible.builtin.include_role:
        name: iambryant.junos.acme
      vars:
        acme_domain_names:
          - acme-test.xserve.cc
        acme_email: "email@example.com"
