---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    # We set the working directory to "roles/${{ matrix.role }}" for molecule,
    # but we need to look back in the home directory so containerlab knows
    # we're logged in to ghcr.io
    - name: "Ensure containerlab topology is deployed"
      ansible.builtin.command: >
        containerlab deploy
        -t {{ lookup('env', 'GITHUB_WORKSPACE') }}/clab-tests/vsrx-testing.clab.yml
      changed_when: true
