---
- name: Prepare
  hosts: all
  tasks:
    - name: Wait for NETCONF port 830 to be ready
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: 830
        state: started
        delay: 5
        timeout: 300
