---
acme_ca_profile_name: "Lets_Encrypt"
acme_ca_identity: "Lets_Encrypt"
acme_url: "https://acme-v02.api.letsencrypt.org/directory"

acme_key_type: "ecdsa"
acme_key_size: "256"

acme_key_id: "ACME-KEY"
acme_certificate_id: "ACME-CERT"

acme_domain_name: ""
acme_email: ""

acme_security_zone: "untrust"
acme_security_zone_interface: "ge-0/0/0.0"
