---
acme_ca_profile_name: "Lets_Encrypt"
acme_ca_identity: "Lets_Encrypt"
acme_url: "https://acme-v02.api.letsencrypt.org/directory"

acme_key_type: "ecdsa"
acme_key_size: "256"

acme_key_id: "ACME-ACCOUNT-KEY"

acme_domain_names: []
acme_email: ""

acme_security_zone: "untrust"
acme_security_zone_interface: "ge-0/0/0.0"

acme_timeout: 30
